version: '3.8'
services:
  app:
    build: .
    command: bash -c "python src/prepare_data.py && coverage run src/unit_tests/test_prepare_data.py && coverage report -m"
    ports:
      - 8000:8000
    image: proshian/mle-mines-vs-rocks:latest
    volumes:
      - ./data:/app/data