version: '3.8'
services:
  app:
    build: .
    command: >
      sh -c "python src/prepare_data.py &&
             python src/train.py &&
             python src/functional_test.py &&
             coverage run src/unit_tests/test_prepare_data.py &&
             coverage run -a src/unit_tests/test_dataset.py &&
             coverage run -a src/unit_tests/test_model.py &&
             coverage report -m
      "
    ports:
      - 8000:8000
    image: proshian/mle-mines-vs-rocks:latest
    volumes:
      - ./data:/app/data